### PR TITLE
Add relationship service for Animaniacs

### PR DESCRIPTION
**Pull request by Blackbaud-IsaacAggrey**
@blackbaud/micro-cervezas please review and merge

### CODE REVIEW

**Comment by Blackbaud-IsaacAggrey** [comment]
cc @blackbaud/animaniacs

**Comment by Blackbaud-DiHuynh** [comment]
PS: everyone should have permission to merge PRs into this repo and re-deploy the action board. You don't need to wait on Micro anymore :)

**Comment by Blackbaud-IsaacAggrey** [comment]
Cool thanks @Blackbaud-DiHuynh - might want to change your PR template in that case!

**Comment by Blackbaud-DiHuynh** [comment]
Oh good catch!

**Pull request merged**
